"""empty message

Revision ID: 01b80c25e7e9
Revises: 5cba53fc2d5e
Create Date: 2023-01-13 14:05:35.220651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01b80c25e7e9'
down_revision = '5cba53fc2d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netp_questionnaires')
    op.drop_index('ix_netp_auditors_questionnaire_id', table_name='netp_auditors')
    op.drop_table('netp_auditors')
    op.drop_index('ix_netp_questionnaire_sections_questionnaire_id', table_name='netp_questionnaire_sections')
    op.drop_table('netp_questionnaire_sections')
    op.add_column('netp_answers', sa.Column('inspection_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_answers_member_id', table_name='netp_answers')
    op.create_index(op.f('ix_netp_answers_inspection_id'), 'netp_answers', ['inspection_id'], unique=False)
    op.drop_constraint('netp_answers_ibfk_1', 'netp_answers', type_='foreignkey')
    op.create_foreign_key(None, 'netp_answers', 'netp_inspections', ['inspection_id'], ['id'])
    op.drop_column('netp_answers', 'member_id')
    op.add_column('netp_questions', sa.Column('inspection_form_section_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_questions_section_id', table_name='netp_questions')
    op.create_index(op.f('ix_netp_questions_inspection_form_section_id'), 'netp_questions', ['inspection_form_section_id'], unique=False)
    op.drop_constraint('netp_questions_ibfk_1', 'netp_questions', type_='foreignkey')
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_form_sections', ['inspection_form_section_id'], ['id'])
    op.drop_column('netp_questions', 'updated_on')
    op.drop_column('netp_questions', 'section_id')
    op.drop_column('netp_questions', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_questions', sa.Column('created_on', mysql.DATETIME(), nullable=True))
    op.add_column('netp_questions', sa.Column('section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('netp_questions', sa.Column('updated_on', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.create_foreign_key('netp_questions_ibfk_1', 'netp_questions', 'netp_questionnaire_sections', ['section_id'], ['id'])
    op.drop_index(op.f('ix_netp_questions_inspection_form_section_id'), table_name='netp_questions')
    op.create_index('ix_netp_questions_section_id', 'netp_questions', ['section_id'], unique=False)
    op.drop_column('netp_questions', 'inspection_form_section_id')
    op.add_column('netp_answers', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.create_foreign_key('netp_answers_ibfk_1', 'netp_answers', 'netp_members', ['member_id'], ['id'])
    op.drop_index(op.f('ix_netp_answers_inspection_id'), table_name='netp_answers')
    op.create_index('ix_netp_answers_member_id', 'netp_answers', ['member_id'], unique=False)
    op.drop_column('netp_answers', 'inspection_id')
    op.create_table('netp_questionnaire_sections',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('section_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('questionnaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], name='netp_questionnaire_sections_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_netp_questionnaire_sections_questionnaire_id', 'netp_questionnaire_sections', ['questionnaire_id'], unique=False)
    op.create_table('netp_auditors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('questionnaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], name='netp_auditors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_netp_auditors_questionnaire_id', 'netp_auditors', ['questionnaire_id'], unique=False)
    op.create_table('netp_questionnaires',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
