"""empty message

Revision ID: 1b913e789569
Revises: c227929121a6
Create Date: 2023-01-08 01:50:49.886142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b913e789569'
down_revision = 'c227929121a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_questionnaire_auditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_member_id', sa.Integer(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['netp_auditors.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_member_id'], ['netp_questionnaire_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questionnaire_auditors_auditor_id'), 'netp_questionnaire_auditors', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_netp_questionnaire_auditors_questionnaire_member_id'), 'netp_questionnaire_auditors', ['questionnaire_member_id'], unique=False)
    op.create_table('netp_questionnaire_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_auditor_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['netp_members.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_auditor_id'], ['netp_questionnaire_auditors.id'], ),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questionnaire_member_member_id'), 'netp_questionnaire_member', ['member_id'], unique=False)
    op.create_index(op.f('ix_netp_questionnaire_member_questionnaire_auditor_id'), 'netp_questionnaire_member', ['questionnaire_auditor_id'], unique=False)
    op.create_index(op.f('ix_netp_questionnaire_member_questionnaire_id'), 'netp_questionnaire_member', ['questionnaire_id'], unique=False)
    op.add_column('netp_answers', sa.Column('questionnaire_member_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_answers_member_id', table_name='netp_answers')
    op.create_index(op.f('ix_netp_answers_questionnaire_member_id'), 'netp_answers', ['questionnaire_member_id'], unique=False)
    op.drop_constraint('netp_answers_ibfk_1', 'netp_answers', type_='foreignkey')
    op.create_foreign_key(None, 'netp_answers', 'netp_questionnaire_member', ['questionnaire_member_id'], ['id'])
    op.drop_column('netp_answers', 'member_id')
    op.drop_index('ix_netp_auditors_questionnaire_id', table_name='netp_auditors')
    op.drop_constraint('netp_auditors_ibfk_1', 'netp_auditors', type_='foreignkey')
    op.drop_column('netp_auditors', 'questionnaire_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_auditors', sa.Column('questionnaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('netp_auditors_ibfk_1', 'netp_auditors', 'netp_questionnaires', ['questionnaire_id'], ['id'])
    op.create_index('ix_netp_auditors_questionnaire_id', 'netp_auditors', ['questionnaire_id'], unique=False)
    op.add_column('netp_answers', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.create_foreign_key('netp_answers_ibfk_1', 'netp_answers', 'netp_members', ['member_id'], ['id'])
    op.drop_index(op.f('ix_netp_answers_questionnaire_member_id'), table_name='netp_answers')
    op.create_index('ix_netp_answers_member_id', 'netp_answers', ['member_id'], unique=False)
    op.drop_column('netp_answers', 'questionnaire_member_id')
    op.drop_index(op.f('ix_netp_questionnaire_member_questionnaire_id'), table_name='netp_questionnaire_member')
    op.drop_index(op.f('ix_netp_questionnaire_member_questionnaire_auditor_id'), table_name='netp_questionnaire_member')
    op.drop_index(op.f('ix_netp_questionnaire_member_member_id'), table_name='netp_questionnaire_member')
    op.drop_table('netp_questionnaire_member')
    op.drop_index(op.f('ix_netp_questionnaire_auditors_questionnaire_member_id'), table_name='netp_questionnaire_auditors')
    op.drop_index(op.f('ix_netp_questionnaire_auditors_auditor_id'), table_name='netp_questionnaire_auditors')
    op.drop_table('netp_questionnaire_auditors')
    # ### end Alembic commands ###
