"""empty message

Revision ID: 25c277d3bb87
Revises: 49e30fc6c1a2
Create Date: 2023-01-11 17:28:45.570669

"""
from alembic import op
import sqlalchemy as sa
import flask_authorize


# revision identifiers, used by Alembic.
revision = '25c277d3bb87'
down_revision = '49e30fc6c1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('netp_members', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_members', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_members', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_members', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_members', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_members', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_column('netp_members', 'group_permissions')
    op.drop_column('netp_members', 'group_id')
    op.drop_column('netp_members', 'owner_permissions')
    op.drop_column('netp_members', 'owner_id')
    op.drop_column('netp_members', 'other_permissions')
    # ### end Alembic commands ###
