"""empty message

Revision ID: 280a06f2fc75
Revises: 01b80c25e7e9
Create Date: 2023-01-13 14:41:29.362250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280a06f2fc75'
down_revision = '01b80c25e7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catName', sa.String(length=100), nullable=False),
    sa.Column('catDescription', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspection_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('additional_details', sa.String(length=1000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regNo', sa.BigInteger(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('regNo')
    )
    op.create_table('netp_contactpersons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_firstName', sa.String(length=100), nullable=False),
    sa.Column('c_lastName', sa.String(length=100), nullable=False),
    sa.Column('c_position', sa.String(length=100), nullable=False),
    sa.Column('c_phone', sa.String(length=100), nullable=False),
    sa.Column('c_workphone', sa.String(length=100), nullable=False),
    sa.Column('c_email', sa.String(length=100), nullable=True),
    sa.Column('c_memberID', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_memberID'], ['netp_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_contactpersons_c_memberID'), 'netp_contactpersons', ['c_memberID'], unique=False)
    op.create_table('netp_inspection_form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), 'netp_inspection_form_sections', ['inspection_form_id'], unique=False)
    op.create_table('netp_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['netp_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspections_inspection_form_id'), 'netp_inspections', ['inspection_form_id'], unique=False)
    op.create_index(op.f('ix_netp_inspections_member_id'), 'netp_inspections', ['member_id'], unique=False)
    op.create_table('netp_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.String(length=100), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryID'], ['netp_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_product_categoryID'), 'netp_product', ['categoryID'], unique=False)
    op.create_table('netp_inspection_inspectors',
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['netp_inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['netp_inspectors.id'], )
    )
    op.create_table('netp_productCategories',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('netp_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netp_category'], ['netp_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['netp_product.id'], )
    )
    op.create_table('netp_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('inspection_form_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_section_id'], ['netp_inspection_form_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questions_inspection_form_section_id'), 'netp_questions', ['inspection_form_section_id'], unique=False)
    op.create_table('netp_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['netp_inspections.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['netp_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_answers_inspection_id'), 'netp_answers', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_netp_answers_question_id'), 'netp_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_netp_answers_question_id'), table_name='netp_answers')
    op.drop_index(op.f('ix_netp_answers_inspection_id'), table_name='netp_answers')
    op.drop_table('netp_answers')
    op.drop_index(op.f('ix_netp_questions_inspection_form_section_id'), table_name='netp_questions')
    op.drop_table('netp_questions')
    op.drop_table('netp_productCategories')
    op.drop_table('netp_inspection_inspectors')
    op.drop_index(op.f('ix_netp_product_categoryID'), table_name='netp_product')
    op.drop_table('netp_product')
    op.drop_index(op.f('ix_netp_inspections_member_id'), table_name='netp_inspections')
    op.drop_index(op.f('ix_netp_inspections_inspection_form_id'), table_name='netp_inspections')
    op.drop_table('netp_inspections')
    op.drop_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), table_name='netp_inspection_form_sections')
    op.drop_table('netp_inspection_form_sections')
    op.drop_index(op.f('ix_netp_contactpersons_c_memberID'), table_name='netp_contactpersons')
    op.drop_table('netp_contactpersons')
    op.drop_table('netp_members')
    op.drop_table('netp_inspectors')
    op.drop_table('netp_inspection_forms')
    op.drop_table('netp_category')
    # ### end Alembic commands ###
