"""empty message

Revision ID: 2e0ac4ddafde
Revises: c360b0334a33
Create Date: 2023-01-08 16:01:27.984493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e0ac4ddafde'
down_revision = 'c360b0334a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('netp_application', sa.Column('businessType', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('companyDescription', sa.String(length=155), nullable=True))
    op.create_foreign_key(None, 'netp_application', 'netp_membershipsubcat', ['memberSubCategoryID'], ['id'])
    op.add_column('netp_members', sa.Column('membershipTypeID', sa.Integer(), nullable=True))
    op.add_column('netp_members', sa.Column('membershipSubCatID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'netp_members', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.drop_column('netp_members', 'membershipID')
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.add_column('netp_members', sa.Column('membershipID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_column('netp_members', 'membershipSubCatID')
    op.drop_column('netp_members', 'membershipTypeID')
    op.drop_column('netp_application', 'companyDescription')
    op.drop_column('netp_application', 'businessType')
    # ### end Alembic commands ###
