"""empty message

Revision ID: 364838d0c20a
Revises: 40cc25b1ecf4
Create Date: 2023-01-03 15:16:02.973616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '364838d0c20a'
down_revision = '40cc25b1ecf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_membershipsubcat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('typeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['typeID'], ['netp_membertype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netp_membershipsubcat')
    # ### end Alembic commands ###
