"""empty message

Revision ID: 4733d4d57620
Revises: e8ba4d9a7156
Create Date: 2023-01-21 22:01:55.037452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4733d4d57620'
down_revision = 'e8ba4d9a7156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'netp_answers', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_answers', 'netp_inspections', ['inspection_id'], ['id'])
    op.create_foreign_key(None, 'netp_answers', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_answers', 'netp_questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'users', ['memberID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_product', ['productID'], ['id'])
    op.create_foreign_key(None, 'netp_application_files', 'netp_application', ['applicationID'], ['id'])
    op.create_foreign_key(None, 'netp_contactpersons', 'users', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_form_sections', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_form_sections', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_form_sections', 'netp_inspection_forms', ['inspection_form_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_forms', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_forms', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_inspectors', 'netp_inspectors', ['inspector_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_inspectors', 'netp_inspections', ['inspection_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspections', 'netp_inspection_forms', ['inspection_form_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspections', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspections', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspections', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspectors', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspectors', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'users', ['userID'], ['id'])
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'users', ['added_by'], ['id'])
    op.add_column('netp_questions', sa.Column('form_id', sa.Integer(), nullable=True))
    op.add_column('netp_questions', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_questions_inspection_form_section_id', table_name='netp_questions')
    op.create_index(op.f('ix_netp_questions_form_id'), 'netp_questions', ['form_id'], unique=False)
    op.create_index(op.f('ix_netp_questions_section_id'), 'netp_questions', ['section_id'], unique=False)
    op.create_foreign_key(None, 'netp_questions', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_form_sections', ['section_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_forms', ['form_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'users', ['owner_id'], ['id'])
    op.drop_column('netp_questions', 'inspection_form_section_id')
    op.create_foreign_key(None, 'ntep_user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'ntep_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.add_column('netp_questions', sa.Column('inspection_form_section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_index(op.f('ix_netp_questions_section_id'), table_name='netp_questions')
    op.drop_index(op.f('ix_netp_questions_form_id'), table_name='netp_questions')
    op.create_index('ix_netp_questions_inspection_form_section_id', 'netp_questions', ['inspection_form_section_id'], unique=False)
    op.drop_column('netp_questions', 'section_id')
    op.drop_column('netp_questions', 'form_id')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspectors', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspectors', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_inspectors', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_inspectors', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_forms', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_forms', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_form_sections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_form_sections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_form_sections', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.drop_constraint(None, 'netp_application_files', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    # ### end Alembic commands ###
