"""empty message

Revision ID: 49e30fc6c1a2
Revises: eb68ed5a05fc
Create Date: 2023-01-11 11:46:39.914033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e30fc6c1a2'
down_revision = 'eb68ed5a05fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_product', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('netp_product', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netp_product', 'updated_on')
    op.drop_column('netp_product', 'date_added')
    # ### end Alembic commands ###
