"""empty message

Revision ID: 5cba53fc2d5e
Revises: 1b913e789569
Create Date: 2023-01-12 12:44:19.851531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cba53fc2d5e'
down_revision = '1b913e789569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_inspection_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('additional_details', sa.String(length=1000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspection_form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), 'netp_inspection_form_sections', ['inspection_form_id'], unique=False)
    op.create_table('netp_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['netp_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspections_inspection_form_id'), 'netp_inspections', ['inspection_form_id'], unique=False)
    op.create_index(op.f('ix_netp_inspections_member_id'), 'netp_inspections', ['member_id'], unique=False)
    op.create_table('netp_inspection_inspectors',
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['netp_inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['netp_inspectors.id'], )
    )
    op.drop_index('ix_netp_auditors_questionnaire_id', table_name='netp_auditors')
    op.drop_table('netp_auditors')
    op.drop_index('ix_netp_questionnaire_sections_questionnaire_id', table_name='netp_questionnaire_sections')
    op.drop_table('netp_questionnaire_sections')
    op.drop_table('netp_questionnaires')
    op.add_column('netp_answers', sa.Column('inspection_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_answers_member_id', table_name='netp_answers')
    op.create_index(op.f('ix_netp_answers_inspection_id'), 'netp_answers', ['inspection_id'], unique=False)
    op.drop_constraint('netp_answers_ibfk_1', 'netp_answers', type_='foreignkey')
    op.create_foreign_key(None, 'netp_answers', 'netp_inspections', ['inspection_id'], ['id'])
    op.drop_column('netp_answers', 'member_id')
    op.add_column('netp_questions', sa.Column('inspection_form_sections_id', sa.Integer(), nullable=True))
    op.drop_index('ix_netp_questions_section_id', table_name='netp_questions')
    op.create_index(op.f('ix_netp_questions_inspection_form_sections_id'), 'netp_questions', ['inspection_form_sections_id'], unique=False)
    op.drop_constraint('netp_questions_ibfk_1', 'netp_questions', type_='foreignkey')
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_form_sections', ['inspection_form_sections_id'], ['id'])
    op.drop_column('netp_questions', 'created_on')
    op.drop_column('netp_questions', 'updated_on')
    op.drop_column('netp_questions', 'section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_questions', sa.Column('section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('netp_questions', sa.Column('updated_on', mysql.DATETIME(), nullable=True))
    op.add_column('netp_questions', sa.Column('created_on', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.create_foreign_key('netp_questions_ibfk_1', 'netp_questions', 'netp_questionnaire_sections', ['section_id'], ['id'])
    op.drop_index(op.f('ix_netp_questions_inspection_form_sections_id'), table_name='netp_questions')
    op.create_index('ix_netp_questions_section_id', 'netp_questions', ['section_id'], unique=False)
    op.drop_column('netp_questions', 'inspection_form_sections_id')
    op.add_column('netp_answers', sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.create_foreign_key('netp_answers_ibfk_1', 'netp_answers', 'netp_members', ['member_id'], ['id'])
    op.drop_index(op.f('ix_netp_answers_inspection_id'), table_name='netp_answers')
    op.create_index('ix_netp_answers_member_id', 'netp_answers', ['member_id'], unique=False)
    op.drop_column('netp_answers', 'inspection_id')
    op.create_table('netp_questionnaires',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('netp_questionnaire_sections',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('section_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('questionnaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], name='netp_questionnaire_sections_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_netp_questionnaire_sections_questionnaire_id', 'netp_questionnaire_sections', ['questionnaire_id'], unique=False)
    op.create_table('netp_auditors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('questionnaire_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], name='netp_auditors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_netp_auditors_questionnaire_id', 'netp_auditors', ['questionnaire_id'], unique=False)
    op.drop_table('netp_inspection_inspectors')
    op.drop_index(op.f('ix_netp_inspections_member_id'), table_name='netp_inspections')
    op.drop_index(op.f('ix_netp_inspections_inspection_form_id'), table_name='netp_inspections')
    op.drop_table('netp_inspections')
    op.drop_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), table_name='netp_inspection_form_sections')
    op.drop_table('netp_inspection_form_sections')
    op.drop_table('netp_inspectors')
    op.drop_table('netp_inspection_forms')
    # ### end Alembic commands ###
