"""empty message

Revision ID: 661c5f20722e
Revises: 72c70e0989e9
Create Date: 2023-01-09 12:39:16.866692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_authorize

# revision identifiers, used by Alembic.
revision = '661c5f20722e'
down_revision = '72c70e0989e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_product', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_product', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_product', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_product', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_product', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netp_product', 'group_permissions')
    op.drop_column('netp_product', 'group_id')
    op.drop_column('netp_product', 'owner_permissions')
    op.drop_column('netp_product', 'owner_id')
    op.drop_column('netp_product', 'other_permissions')
    # ### end Alembic commands ###
