"""empty message

Revision ID: 6e51a13d3934
Revises: 661c5f20722e
Create Date: 2023-01-09 13:55:34.760943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e51a13d3934'
down_revision = '661c5f20722e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('netp_product', 'owner_id')
    op.drop_column('netp_product', 'group_permissions')
    op.drop_column('netp_product', 'owner_permissions')
    op.drop_column('netp_product', 'other_permissions')
    op.drop_column('netp_product', 'group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_product', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('netp_product', sa.Column('other_permissions', mysql.TEXT(), nullable=True))
    op.add_column('netp_product', sa.Column('owner_permissions', mysql.TEXT(), nullable=True))
    op.add_column('netp_product', sa.Column('group_permissions', mysql.TEXT(), nullable=True))
    op.add_column('netp_product', sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
