"""empty message

Revision ID: 71b3bc810849
Revises: b770b9eb7c82
Create Date: 2022-12-20 22:22:17.212019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71b3bc810849'
down_revision = 'b770b9eb7c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_productCategories',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('netp_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netp_category'], ['netp_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['netp_product.id'], )
    )
    op.drop_table('netp_productcategories')
    op.create_foreign_key(None, 'netp_contactpersons', 'netp_members', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membertype', ['membershipID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.create_table('netp_productcategories',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('netp_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('netp_productCategories')
    # ### end Alembic commands ###
