"""empty message

Revision ID: 72c70e0989e9
Revises: b7e22ca86fe8
Create Date: 2023-01-09 11:55:19.997540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_authorize

# revision identifiers, used by Alembic.
revision = '72c70e0989e9'
down_revision = 'b7e22ca86fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntep_roles', sa.Column('restrictions', flask_authorize.mixins.JSON(), nullable=True))
    op.drop_column('ntep_roles', 'allowances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntep_roles', sa.Column('allowances', mysql.TEXT(), nullable=True))
    op.drop_column('ntep_roles', 'restrictions')
    # ### end Alembic commands ###
