"""empty message

Revision ID: b41a502e5f60
Revises: 25c277d3bb87
Create Date: 2023-01-13 11:25:01.506163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b41a502e5f60'
down_revision = '25c277d3bb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'netp_application', 'netp_members', ['memberID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_product', ['productID'], ['id'])
    op.create_foreign_key(None, 'netp_contactpersons', 'netp_members', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'ntep_groups', ['group_id'], ['id'])
    op.drop_column('netp_members', 'date_joined')
    op.drop_column('netp_members', 'updated_on')
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'ntep_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_member', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_on')
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'created_on')
    op.drop_column('users', 'is_member')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.add_column('netp_members', sa.Column('updated_on', mysql.DATETIME(), nullable=True))
    op.add_column('netp_members', sa.Column('date_joined', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    # ### end Alembic commands ###
