"""empty message

Revision ID: b5201963a6d4
Revises: c391067ea3db
Create Date: 2023-01-19 13:15:21.057578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5201963a6d4'
down_revision = 'c391067ea3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_inspection_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('additional_details', sa.String(length=1000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_inspection_form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), 'netp_inspection_form_sections', ['inspection_form_id'], unique=False)
    op.create_table('netp_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_form_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_id'], ['netp_inspection_forms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_inspections_inspection_form_id'), 'netp_inspections', ['inspection_form_id'], unique=False)
    op.create_index(op.f('ix_netp_inspections_user_id'), 'netp_inspections', ['user_id'], unique=False)
    op.create_table('netp_inspection_inspectors',
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['netp_inspections.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['netp_inspectors.id'], )
    )
    op.create_table('netp_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('inspection_form_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_form_section_id'], ['netp_inspection_form_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questions_inspection_form_section_id'), 'netp_questions', ['inspection_form_section_id'], unique=False)
    op.create_table('netp_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['netp_inspections.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['netp_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_answers_inspection_id'), 'netp_answers', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_netp_answers_question_id'), 'netp_answers', ['question_id'], unique=False)
    op.create_foreign_key(None, 'netp_application', 'netp_product', ['productID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'users', ['memberID'], ['id'])
    op.create_foreign_key(None, 'netp_application_files', 'netp_application', ['applicationID'], ['id'])
    op.create_foreign_key(None, 'netp_contactpersons', 'users', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.create_foreign_key(None, 'netp_member_details', 'users', ['userID'], ['id'])
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'users', ['added_by'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'ntep_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_member_details', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.drop_constraint(None, 'netp_application_files', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_index(op.f('ix_netp_answers_question_id'), table_name='netp_answers')
    op.drop_index(op.f('ix_netp_answers_inspection_id'), table_name='netp_answers')
    op.drop_table('netp_answers')
    op.drop_index(op.f('ix_netp_questions_inspection_form_section_id'), table_name='netp_questions')
    op.drop_table('netp_questions')
    op.drop_table('netp_inspection_inspectors')
    op.drop_index(op.f('ix_netp_inspections_user_id'), table_name='netp_inspections')
    op.drop_index(op.f('ix_netp_inspections_inspection_form_id'), table_name='netp_inspections')
    op.drop_table('netp_inspections')
    op.drop_index(op.f('ix_netp_inspection_form_sections_inspection_form_id'), table_name='netp_inspection_form_sections')
    op.drop_table('netp_inspection_form_sections')
    op.drop_table('netp_inspectors')
    op.drop_table('netp_inspection_forms')
    # ### end Alembic commands ###
