"""empty message

Revision ID: c227929121a6
Revises: ffb22582990d
Create Date: 2023-01-05 00:32:12.526213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c227929121a6'
down_revision = 'ffb22582990d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netp_auditors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_auditors_questionnaire_id'), 'netp_auditors', ['questionnaire_id'], unique=False)
    op.create_table('netp_questionnaire_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('questionnaire_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['netp_questionnaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questionnaire_sections_questionnaire_id'), 'netp_questionnaire_sections', ['questionnaire_id'], unique=False)
    op.create_table('netp_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['netp_questionnaire_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_questions_section_id'), 'netp_questions', ['section_id'], unique=False)
    op.create_table('netp_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['netp_members.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['netp_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_answers_member_id'), 'netp_answers', ['member_id'], unique=False)
    op.create_index(op.f('ix_netp_answers_question_id'), 'netp_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_netp_answers_question_id'), table_name='netp_answers')
    op.drop_index(op.f('ix_netp_answers_member_id'), table_name='netp_answers')
    op.drop_table('netp_answers')
    op.drop_index(op.f('ix_netp_questions_section_id'), table_name='netp_questions')
    op.drop_table('netp_questions')
    op.drop_index(op.f('ix_netp_questionnaire_sections_questionnaire_id'), table_name='netp_questionnaire_sections')
    op.drop_table('netp_questionnaire_sections')
    op.drop_index(op.f('ix_netp_auditors_questionnaire_id'), table_name='netp_auditors')
    op.drop_table('netp_auditors')
    op.drop_table('netp_questionnaires')
    # ### end Alembic commands ###
