"""empty message

Revision ID: c360b0334a33
Revises: df16013b4b2c
Create Date: 2023-01-08 15:51:31.010250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c360b0334a33'
down_revision = 'df16013b4b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_application', sa.Column('businessType', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('companyDescription', sa.String(length=155), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netp_application', 'companyDescription')
    op.drop_column('netp_application', 'businessType')
    # ### end Alembic commands ###
