"""empty message

Revision ID: c7f167c12181
Revises: 8f40fa4e1310
Create Date: 2022-12-15 16:12:21.596442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f167c12181'
down_revision = '8f40fa4e1310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_contactpersons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_firstName', sa.String(length=100), nullable=False),
    sa.Column('c_lastName', sa.String(length=100), nullable=False),
    sa.Column('c_position', sa.String(length=100), nullable=False),
    sa.Column('c_phone', sa.String(length=100), nullable=False),
    sa.Column('c_workphone', sa.String(length=100), nullable=False),
    sa.Column('c_email', sa.String(length=100), nullable=True),
    sa.Column('c_memberID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_memberID'], ['netp_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_netp_contactpersons_c_memberID'), 'netp_contactpersons', ['c_memberID'], unique=False)
    op.create_foreign_key(None, 'followers', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'users', ['follower_id'], ['id'])
    op.add_column('netp_members', sa.Column('regNo', sa.BigInteger(), nullable=False))
    op.add_column('netp_members', sa.Column('lastName', sa.String(length=100), nullable=False))
    op.add_column('netp_members', sa.Column('village', sa.String(length=100), nullable=False))
    op.add_column('netp_members', sa.Column('region', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'netp_members', ['regNo'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='unique')
    op.drop_column('netp_members', 'region')
    op.drop_column('netp_members', 'village')
    op.drop_column('netp_members', 'lastName')
    op.drop_column('netp_members', 'regNo')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_index(op.f('ix_netp_contactpersons_c_memberID'), table_name='netp_contactpersons')
    op.drop_table('netp_contactpersons')
    # ### end Alembic commands ###
