"""empty message

Revision ID: d59f65b484c0
Revises: 2e0ac4ddafde
Create Date: 2023-01-08 16:05:31.476971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59f65b484c0'
down_revision = '2e0ac4ddafde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_productCategories',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('netp_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netp_category'], ['netp_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['netp_product.id'], )
    )
    op.create_foreign_key(None, 'netp_application', 'netp_membertype', ['membershipID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_membershipsubcat', ['memberSubCategoryID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_members', ['memberID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_product', ['productID'], ['id'])
    op.create_foreign_key(None, 'netp_contactpersons', 'netp_members', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'ntep_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_table('netp_productCategories')
    # ### end Alembic commands ###
