"""empty message

Revision ID: daf1fa9224bd
Revises: d59f65b484c0
Create Date: 2023-01-08 18:40:21.357314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daf1fa9224bd'
down_revision = 'd59f65b484c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_productCategories',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('netp_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netp_category'], ['netp_category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['netp_product.id'], )
    )
    op.drop_table('netp_productcategories')
    op.add_column('netp_application', sa.Column('companyRegCert', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('exportRegCert', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('companyProfile', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('exportNo', sa.String(), nullable=True))
    op.add_column('netp_application', sa.Column('applicationStatus', sa.String(length=155), nullable=True))
    op.add_column('netp_application', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('netp_application', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_index('ix_netp_application_memberSubCategoryID', table_name='netp_application')
    op.drop_index('ix_netp_application_membershipID', table_name='netp_application')
    op.create_unique_constraint(None, 'netp_application', ['companyRegCert'])
    op.create_unique_constraint(None, 'netp_application', ['exportRegCert'])
    op.create_unique_constraint(None, 'netp_application', ['companyProfile'])
    op.create_unique_constraint(None, 'netp_application', ['exportNo'])
    op.create_foreign_key(None, 'netp_application', 'netp_product', ['productID'], ['id'])
    op.create_foreign_key(None, 'netp_application', 'netp_members', ['memberID'], ['id'])
    op.drop_column('netp_application', 'membershipID')
    op.drop_column('netp_application', 'memberSubCategoryID')
    op.create_foreign_key(None, 'netp_contactpersons', 'netp_members', ['c_memberID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membertype', ['membershipTypeID'], ['id'])
    op.create_foreign_key(None, 'netp_members', 'netp_membershipsubcat', ['membershipSubCatID'], ['id'])
    op.create_foreign_key(None, 'netp_membershipsubcat', 'netp_membertype', ['typeID'], ['id'])
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_group', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'ntep_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'ntep_user_role', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_role', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'ntep_user_group', type_='foreignkey')
    op.drop_constraint(None, 'netp_product', type_='foreignkey')
    op.drop_constraint(None, 'netp_membershipsubcat', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_members', type_='foreignkey')
    op.drop_constraint(None, 'netp_contactpersons', type_='foreignkey')
    op.add_column('netp_application', sa.Column('memberSubCategoryID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('netp_application', sa.Column('membershipID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='foreignkey')
    op.drop_constraint(None, 'netp_application', type_='unique')
    op.drop_constraint(None, 'netp_application', type_='unique')
    op.drop_constraint(None, 'netp_application', type_='unique')
    op.drop_constraint(None, 'netp_application', type_='unique')
    op.create_index('ix_netp_application_membershipID', 'netp_application', ['membershipID'], unique=False)
    op.create_index('ix_netp_application_memberSubCategoryID', 'netp_application', ['memberSubCategoryID'], unique=False)
    op.drop_column('netp_application', 'updated_on')
    op.drop_column('netp_application', 'created_on')
    op.drop_column('netp_application', 'applicationStatus')
    op.drop_column('netp_application', 'exportNo')
    op.drop_column('netp_application', 'companyProfile')
    op.drop_column('netp_application', 'exportRegCert')
    op.drop_column('netp_application', 'companyRegCert')
    op.create_table('netp_productcategories',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('netp_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('netp_productCategories')
    # ### end Alembic commands ###
