"""empty message

Revision ID: eb68ed5a05fc
Revises: 6e51a13d3934
Create Date: 2023-01-11 11:33:01.186344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_authorize

# revision identifiers, used by Alembic.
revision = 'eb68ed5a05fc'
down_revision = '6e51a13d3934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('netp_productcategories')
    op.create_foreign_key(None, 'netp_product', 'netp_category', ['categoryID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netp_productcategories',
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('netp_category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
