"""empty message

Revision ID: ec2b249f7b5f
Revises: 4733d4d57620
Create Date: 2023-01-21 23:52:31.266666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import flask_authorize

# revision identifiers, used by Alembic.
revision = 'ec2b249f7b5f'
down_revision = '4733d4d57620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_answers', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_answers', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_answers', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_answers', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_answers', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_answers', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_answers', 'users', ['owner_id'], ['id'])
    op.add_column('netp_inspection_form_sections', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspection_form_sections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspection_form_sections', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspection_form_sections', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspection_form_sections', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_inspection_form_sections', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_form_sections', 'users', ['owner_id'], ['id'])
    op.add_column('netp_inspection_forms', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspection_forms', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspection_forms', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspection_forms', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspection_forms', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_inspection_forms', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspection_forms', 'ntep_groups', ['group_id'], ['id'])
    op.add_column('netp_inspections', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspections', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspections', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspections', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspections', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_inspections', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspections', 'users', ['owner_id'], ['id'])
    op.add_column('netp_inspectors', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspectors', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspectors', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_inspectors', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_inspectors', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.create_foreign_key(None, 'netp_inspectors', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_inspectors', 'users', ['owner_id'], ['id'])
    op.add_column('netp_questions', sa.Column('form_id', sa.Integer(), nullable=True))
    op.add_column('netp_questions', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('netp_questions', sa.Column('other_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_questions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('netp_questions', sa.Column('owner_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.add_column('netp_questions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('netp_questions', sa.Column('group_permissions', flask_authorize.mixins.PipedList(), nullable=True))
    op.drop_index('ix_netp_questions_inspection_form_section_id', table_name='netp_questions')
    op.create_index(op.f('ix_netp_questions_form_id'), 'netp_questions', ['form_id'], unique=False)
    op.create_index(op.f('ix_netp_questions_section_id'), 'netp_questions', ['section_id'], unique=False)
    op.drop_constraint('netp_questions_ibfk_1', 'netp_questions', type_='foreignkey')
    op.create_foreign_key(None, 'netp_questions', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_forms', ['form_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'ntep_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'netp_questions', 'netp_inspection_form_sections', ['section_id'], ['id'])
    op.drop_column('netp_questions', 'inspection_form_section_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netp_questions', sa.Column('inspection_form_section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.drop_constraint(None, 'netp_questions', type_='foreignkey')
    op.create_foreign_key('netp_questions_ibfk_1', 'netp_questions', 'netp_inspection_form_sections', ['inspection_form_section_id'], ['id'])
    op.drop_index(op.f('ix_netp_questions_section_id'), table_name='netp_questions')
    op.drop_index(op.f('ix_netp_questions_form_id'), table_name='netp_questions')
    op.create_index('ix_netp_questions_inspection_form_section_id', 'netp_questions', ['inspection_form_section_id'], unique=False)
    op.drop_column('netp_questions', 'group_permissions')
    op.drop_column('netp_questions', 'group_id')
    op.drop_column('netp_questions', 'owner_permissions')
    op.drop_column('netp_questions', 'owner_id')
    op.drop_column('netp_questions', 'other_permissions')
    op.drop_column('netp_questions', 'section_id')
    op.drop_column('netp_questions', 'form_id')
    op.drop_constraint(None, 'netp_inspectors', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspectors', type_='foreignkey')
    op.drop_column('netp_inspectors', 'group_permissions')
    op.drop_column('netp_inspectors', 'group_id')
    op.drop_column('netp_inspectors', 'owner_permissions')
    op.drop_column('netp_inspectors', 'owner_id')
    op.drop_column('netp_inspectors', 'other_permissions')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspections', type_='foreignkey')
    op.drop_column('netp_inspections', 'group_permissions')
    op.drop_column('netp_inspections', 'group_id')
    op.drop_column('netp_inspections', 'owner_permissions')
    op.drop_column('netp_inspections', 'owner_id')
    op.drop_column('netp_inspections', 'other_permissions')
    op.drop_constraint(None, 'netp_inspection_forms', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_forms', type_='foreignkey')
    op.drop_column('netp_inspection_forms', 'group_permissions')
    op.drop_column('netp_inspection_forms', 'group_id')
    op.drop_column('netp_inspection_forms', 'owner_permissions')
    op.drop_column('netp_inspection_forms', 'owner_id')
    op.drop_column('netp_inspection_forms', 'other_permissions')
    op.drop_constraint(None, 'netp_inspection_form_sections', type_='foreignkey')
    op.drop_constraint(None, 'netp_inspection_form_sections', type_='foreignkey')
    op.drop_column('netp_inspection_form_sections', 'group_permissions')
    op.drop_column('netp_inspection_form_sections', 'group_id')
    op.drop_column('netp_inspection_form_sections', 'owner_permissions')
    op.drop_column('netp_inspection_form_sections', 'owner_id')
    op.drop_column('netp_inspection_form_sections', 'other_permissions')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.drop_constraint(None, 'netp_answers', type_='foreignkey')
    op.drop_column('netp_answers', 'group_permissions')
    op.drop_column('netp_answers', 'group_id')
    op.drop_column('netp_answers', 'owner_permissions')
    op.drop_column('netp_answers', 'owner_id')
    op.drop_column('netp_answers', 'other_permissions')
    # ### end Alembic commands ###
